//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ProductSalesStatus
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int CurrentStock { get; set; }
        public int TotalUnitsSold { get; set; }
    }
}
